repos:
  # python
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.263
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        exclude: ^(tests)|(docs)
        require_serial: true
        args: ["--explicit-package-bases", "--check-untyped-defs"]
        additional_dependencies:
          ["arq>=0.25.0", "colorama>=0.4.6", "dill>=0.3.6", "types-colorama"]

  # docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
