version: "3"
services:
  redis-storage:
    image: redis:alpine

  test:
    build: .
    container_name: jj-testing
    volumes:
      - ./:/home/developer/just-jobs
    depends_on:
      - redis-storage
