[tool.poetry]
name = "just-jobs"
version = "0.1.0"
description = "A lightweight asynchronous Python job executor backed by Redis."
authors = ["Elias Gabriel <me@eliasfgabriel.com>"]

[tool.poetry.dependencies]
python = "^3.6.2"
aioredis = {extras = ["hiredis"], version = "^2.0.0"}
anyio = "^3.3.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.2"
mypy = "^0.910"
flake8 = "^3.9.2"
hypothesis = "^6.14.3"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
show_column_numbers = true
follow_imports = "silent"
warn_unreachable = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
