name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_CACHE_DIR: ~/.cache/poetry
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2.1.2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.POETRY_CACHE_DIR }}
            .venv
          key: linting-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install -n --no-root --no-dev -E linting
      - name: Check formatting
        run: poetry run black --check --diff .
      - name: Check typing
        run: poetry run mypy --pretty .

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false
    env:
      POETRY_CACHE_DIR: ~/.cache/poetry
    name: ${{ matrix.os }}_${{ matrix.py-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - uses: abatilo/actions-poetry@v2.1.2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.POETRY_CACHE_DIR }}
            .venv
          key: ${{ runner.os }}_${{ matrix.py-version }}_${{ hashFiles('poetry.lock') }}
      - uses: supercharge/redis-github-action@1.2.0
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install -n
      - name: Run tests
        run: poetry run pytest -vv tests
