name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_CACHE_DIR: ~/.cache/poetry
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - uses: abatilo/actions-poetry@v2.1.2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.POETRY_CACHE_DIR }}
            .venv
          key: linting-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install -n --no-root
      - name: Check formatting
        run: poetry run black --check --diff .
      - name: Check typing
        run: poetry run mypy --pretty .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: tests
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose up -d
      - name: Wait for services
        run: sleep 15s
      - name: Run test suite
        run: docker exec jj-testing pytest -svv
